// ENGRAM Demo Mode — Mock data for demonstration videos
// This file is NOT embedded in production builds.
// Load separately: <script src="demo.js"></script>
(function(){
"use strict";

// ── Helpers ──
function D(d){ return new Date(Date.now()-d*864e5).toISOString(); }
function NP(props){ return {properties: props, created_time: D(0)}; }
function T(v){ return {title:[{plain_text:v}]}; }
function R(v){ return {rich_text:[{plain_text:v}]}; }
function N(v){ return {number:v}; }
function S(v){ return {select:{name:v}}; }
function CK(v){ return {checkbox:v}; }
function DT(v){ return {date:{start:v}}; }

// ── DEMO_DATA ──
window.DEMO_DATA = {
'/api/dashboard/health': {results:[
    NP({'Overall Score':N(87),'Decisions Score':N(91),'Pulse Score':N(82),'Shield Score':N(88),'Atlas Score':N(85),'Vault Score':N(79),'Review Score':N(90),'AI Narrative':R('Strong week for the engineering team. Cargo audit clean with zero critical CVEs. 3 RFCs merged including the async runtime migration. Benchmark regression in JSON deserialization caught early and fixed before release. Code review velocity improved 18% with AI-assisted reviews. Knowledge gaps in the cryptography module flagged for onboarding priority.'),'Delta From Last':N(3.2),'Period':R('Week 13 — Mar 23-28, 2026'),'Key Risks':R('Cryptography module has no owner, REDIS_URL missing in production environment, single point of knowledge on Notion API integration'),'Key Wins':R('Zero critical CVEs after hyper patch, 3 RFCs merged ahead of schedule, benchmark regression caught and resolved pre-release')}),
    NP({'Overall Score':N(84),'Decisions Score':N(88),'Pulse Score':N(80),'Shield Score':N(85),'Atlas Score':N(82),'Vault Score':N(77),'Review Score':N(88),'AI Narrative':R('Steady progress. Two new dependencies audited. RFC-012 approved.'),'Delta From Last':N(1.5),'Period':R('Week 12 — Mar 16-22, 2026'),'Key Risks':R('Serde_json deserialization regression detected, pending CVE in ring crate, scheduler test coverage below threshold'),'Key Wins':R('RFC-012 parking_lot migration approved, two new dependencies passed security audit, review velocity up 12%')}),
    NP({'Overall Score':N(82),'Decisions Score':N(85),'Pulse Score':N(78),'Shield Score':N(84),'Atlas Score':N(80),'Vault Score':N(75),'Review Score':N(86),'AI Narrative':R('Minor regression in build times addressed.'),'Delta From Last':N(-0.8),'Period':R('Week 11 — Mar 9-15, 2026'),'Key Risks':R('Build time regression in engram-core, missing integration tests for cron scheduler, documentation gaps in event routing'),'Key Wins':R('Build regression root-caused to debug symbols and fixed, onboarding track generated for new backend hire')}),
    NP({'Overall Score':N(83),'Decisions Score':N(86),'Pulse Score':N(79),'Shield Score':N(83),'Atlas Score':N(81),'Vault Score':N(76),'Review Score':N(87),'AI Narrative':R('New module engram-release shipped.'),'Delta From Last':N(2.1),'Period':R('Week 10 — Mar 2-8, 2026'),'Key Risks':R('engram-release module shipped without full test coverage, deployment runbook still missing, h2 CVE pending patch'),'Key Wins':R('engram-release module shipped on schedule, release gate automation operational, complexity score within target')}),
    NP({'Overall Score':N(81),'Decisions Score':N(84),'Pulse Score':N(77),'Shield Score':N(82),'Atlas Score':N(79),'Vault Score':N(74),'Review Score':N(85),'AI Narrative':R('Sprint planning completed. Focus on security hardening.'),'Delta From Last':N(0.5),'Period':R('Week 9 — Feb 23-Mar 1, 2026'),'Key Risks':R('Multiple unwrap() calls in webhook.rs need error handling, vault rotation policy overdue for SMTP_PASSWORD, openssl-sys CVE unpatched'),'Key Wins':R('Sprint planning aligned team on security hardening priorities, secret rotation logging implemented in Vault agent')}),
    NP({'Overall Score':N(80),'Decisions Score':N(83),'Pulse Score':N(76),'Shield Score':N(81),'Atlas Score':N(78),'Vault Score':N(73),'Review Score':N(84),'AI Narrative':R('Baseline established for Q1.'),'Delta From Last':N(1.0),'Period':R('Week 8 — Feb 16-22, 2026'),'Key Risks':R('Q1 baseline reveals Vault score is the weakest layer at 73, no production deployment runbook exists, bus factor risk on Notion API'),'Key Wins':R('Q1 baseline metrics established across all nine layers, health scoring pipeline fully operational')}),
]},
'/api/dashboard/events': {results:[
    NP({'Event Title':T('RFC-015 Approved: Zero-copy API responses'),'Source Layer':R('Decisions'),'Event Type':R('RFC Approved'),'Timestamp':DT(D(0)),'Is Milestone':CK(true)}),
    NP({'Event Title':T('Critical CVE-2026-1847 patched in hyper 1.6.1'),'Source Layer':R('Shield'),'Event Type':R('Security Patch'),'Timestamp':DT(D(0)),'Is Milestone':CK(true)}),
    NP({'Event Title':T('PR #142 merged: Async webhook handler refactor'),'Source Layer':R('Review'),'Event Type':R('PR Merged'),'Timestamp':DT(D(0)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Benchmark regression detected: serde_json deser +12%'),'Source Layer':R('Pulse'),'Event Type':R('Regression'),'Timestamp':DT(D(1)),'Is Milestone':CK(true)}),
    NP({'Event Title':T('New module mapped: engram-release (complexity: 7.2)'),'Source Layer':R('Atlas'),'Event Type':R('Module Added'),'Timestamp':DT(D(1)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Secret rotation completed: NOTION_MCP_TOKEN'),'Source Layer':R('Vault'),'Event Type':R('Secret Rotated'),'Timestamp':DT(D(1)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Health score improved: 84 → 87 (+3.2)'),'Source Layer':R('Health'),'Event Type':R('Score Change'),'Timestamp':DT(D(1)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('PR #139 review: 2 blockers found in auth middleware'),'Source Layer':R('Review'),'Event Type':R('Review Complete'),'Timestamp':DT(D(2)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Onboarding track generated for Sarah Chen (Backend)'),'Source Layer':R('Atlas'),'Event Type':R('Onboarding'),'Timestamp':DT(D(2)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Release v0.4.0-rc1 gate check: all criteria passed'),'Source Layer':R('Decisions'),'Event Type':R('Release Gate'),'Timestamp':DT(D(2)),'Is Milestone':CK(true)}),
    NP({'Event Title':T('Dependency update: tokio 1.36 → 1.37'),'Source Layer':R('Shield'),'Event Type':R('Dependency Update'),'Timestamp':DT(D(3)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Knowledge gap detected: No owner for crypto module'),'Source Layer':R('Atlas'),'Event Type':R('Gap Detected'),'Timestamp':DT(D(3)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Weekly digest generated for engineering team'),'Source Layer':R('Health'),'Event Type':R('Digest'),'Timestamp':DT(D(4)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('PR #135 merged: Add JWT authentication layer'),'Source Layer':R('Review'),'Event Type':R('PR Merged'),'Timestamp':DT(D(4)),'Is Milestone':CK(false)}),
    NP({'Event Title':T('Environment drift detected: REDIS_URL missing in prod'),'Source Layer':R('Vault'),'Event Type':R('Config Drift'),'Timestamp':DT(D(5)),'Is Milestone':CK(false)}),
]},
'/api/dashboard/rfcs': {results:[
    NP({'RFC ID':R('RFC-015'),'RFC Title':T('Zero-copy deserialization for API responses'),'Status':S('Approved'),'Author':R('Manoj P'),'Description':R('Proposes replacing serde_json owned deserialization with zero-copy borrowing via serde::Deserialize lifetime annotations. This eliminates redundant allocations in hot API paths and reduces p99 latency by an estimated 15-20%.'),'Decision Rationale':R('Implementation closely follows the proposal by introducing a BorrowedResponse<\'a> type in engram-types. The async handler changes align with the RFC scope, though the fallback to owned deserialization for WebSocket frames was not originally specified.'),'Drift Score':N(2),'Drift Notes':R('- WebSocket frame fallback to owned deserialization added outside RFC scope\n- Original proposal did not address backward compatibility for v0.3.x clients\n- All other implementation details match the approved design')}),
    NP({'RFC ID':R('RFC-014'),'RFC Title':T('Migrate webhook handler to async channels'),'Status':S('Approved'),'Author':R('Sarah Chen'),'Description':R('Replaces the synchronous webhook processing pipeline with tokio::sync::mpsc channels for non-blocking event dispatch. The migration decouples webhook ingestion from agent processing, enabling independent backpressure handling.'),'Decision Rationale':R('The channel-based architecture was approved after benchmarks showed 3x throughput improvement under load. The bounded channel size of 1024 was a compromise between memory usage and burst tolerance.'),'Drift Score':N(1),'Drift Notes':R('- Channel buffer size increased from proposed 512 to 1024 based on load test results\n- Implementation matches proposal in all other aspects')}),
    NP({'RFC ID':R('RFC-013'),'RFC Title':T('Add OpenTelemetry tracing spans'),'Status':S('Under Review'),'Author':R('Alex Kim'),'Description':R('Introduces OpenTelemetry distributed tracing across all agent boundaries using the tracing-opentelemetry crate. Spans will capture agent execution time, Notion API latency, and Claude inference duration for end-to-end observability.'),'Decision Rationale':R('Still under review. Initial feedback highlights concerns about trace data volume in production and the need for a sampling strategy. The proposed 100% trace rate may need reduction to 10% for cost management.'),'Drift Score':N(0),'Drift Notes':R('- RFC is under review, no implementation drift to assess yet')}),
    NP({'RFC ID':R('RFC-012'),'RFC Title':T('Replace tokio::sync::Mutex with parking_lot'),'Status':S('Approved'),'Author':R('Manoj P'),'Description':R('Migrates all synchronous mutex usage from tokio::sync::Mutex to parking_lot::Mutex where await points are not held across lock boundaries. This reduces lock contention overhead and eliminates spurious task wake-ups in the scheduler.'),'Decision Rationale':R('Approved after audit confirmed no await points are held across the 14 identified mutex sites. The migration is mechanical and low-risk, with measurable improvement in scheduler throughput.'),'Drift Score':N(0),'Drift Notes':R('- Implementation matches proposal exactly for all 14 mutex migration sites\n- No scope changes detected')}),
    NP({'RFC ID':R('RFC-011'),'RFC Title':T('Implement graceful shutdown for all agents'),'Status':S('Implemented'),'Author':R('James Liu'),'Description':R('Adds coordinated shutdown signaling via tokio::sync::watch channels so all nine agents drain their work queues before process exit. Includes a configurable shutdown timeout defaulting to 30 seconds.'),'Decision Rationale':R('Implementation fully realized the proposal. The watch channel pattern ensures agents receive shutdown signals without polling. The 30-second timeout was validated against the longest observed agent task duration of 12 seconds.'),'Drift Score':N(1),'Drift Notes':R('- Added a force-kill fallback after 2x timeout that was not in original proposal\n- All other implementation details match the approved design')}),
    NP({'RFC ID':R('RFC-010'),'RFC Title':T('Add rate limiting to webhook endpoint'),'Status':S('Implemented'),'Author':R('Sarah Chen'),'Description':R('Implements token bucket rate limiting on the /webhook/github endpoint using tower::limit. The default rate of 100 requests per minute with a burst of 20 protects against GitHub webhook replay storms.'),'Decision Rationale':R('Rate limiter was implemented as proposed using tower middleware. The per-IP tracking was added as an enhancement beyond the original RFC scope to prevent single-source abuse.'),'Drift Score':N(3),'Drift Notes':R('- Per-IP rate tracking added beyond original proposal scope\n- Redis-backed distributed rate limiting deferred to future RFC\n- Rate limit headers (X-RateLimit-Remaining) added but not in original spec')}),
    NP({'RFC ID':R('RFC-009'),'RFC Title':T('Introduce feature flags for experimental agents'),'Status':S('Draft'),'Author':R('Priya Sharma'),'Description':R('Proposes a compile-time feature flag system using Cargo features to gate experimental agents behind opt-in flags. This allows shipping unstable agents in release builds without exposing them to all users.'),'Decision Rationale':R('Draft stage. No implementation decision yet. Early feedback suggests runtime feature flags via config may be preferable to compile-time gating for operational flexibility.'),'Drift Score':N(0),'Drift Notes':R('- RFC is in draft, no implementation drift to assess yet')}),
    NP({'RFC ID':R('RFC-008'),'RFC Title':T('Database connection pooling strategy'),'Status':S('Draft'),'Author':R('Alex Kim'),'Description':R('Outlines a connection pooling strategy using deadpool-postgres with configurable pool sizes per agent. The proposal addresses connection exhaustion observed under concurrent agent scheduling during peak webhook activity.'),'Decision Rationale':R('Draft stage. Discussion ongoing about whether to use deadpool or bb8 as the pool implementation. Benchmarks comparing both libraries are requested before approval.'),'Drift Score':N(0),'Drift Notes':R('- RFC is in draft, no implementation drift to assess yet')}),
]},
'/api/dashboard/vulnerabilities': {results:[
    NP({'Package':T('hyper'),'CVE ID':R('CVE-2026-1847'),'Severity':S('Critical'),'Triage Status':R('Patched'),'Version':R('1.6.0 → 1.6.1'),'AI Triage':R('Critical priority: HTTP request smuggling via malformed Transfer-Encoding headers allows request routing bypass. Patch to hyper 1.6.1 immediately. ENGRAM exposes webhook endpoints directly, making this exploitable in production.')}),
    NP({'Package':T('rustls'),'CVE ID':R('CVE-2026-1523'),'Severity':S('High'),'Triage Status':R('Patched'),'Version':R('0.23.4 → 0.23.5'),'AI Triage':R('High priority: TLS certificate validation bypass in rustls allows man-in-the-middle attacks on outbound Notion API and Claude API connections. Upgrade to 0.23.5 is essential since ENGRAM transmits API keys over these TLS channels.')}),
    NP({'Package':T('serde_json'),'CVE ID':R('CVE-2026-0891'),'Severity':S('Medium'),'Triage Status':R('Accepted'),'Version':R('1.0.114'),'AI Triage':R('Medium risk: Stack overflow via deeply nested JSON payloads. Accepted because ENGRAM webhook payloads from GitHub have a max depth of 5 levels. Add input depth validation as defense-in-depth when convenient.')}),
    NP({'Package':T('ring'),'CVE ID':R('CVE-2026-0743'),'Severity':S('High'),'Triage Status':R('Monitoring'),'Version':R('0.17.7'),'AI Triage':R('High risk but no patch available yet. Timing side-channel in ECDSA signature verification could leak private key material. ENGRAM uses ring indirectly via rustls for TLS. Monitor upstream for 0.17.8 release and patch within 48 hours of availability.')}),
    NP({'Package':T('tokio'),'CVE ID':R('CVE-2026-0612'),'Severity':S('Low'),'Triage Status':R('Dismissed'),'Version':R('1.36.0'),'AI Triage':R('Low risk: Theoretical resource exhaustion in io_uring backend under specific Linux kernel versions. Dismissed because ENGRAM deploys on standard epoll-based tokio runtime and does not enable the io_uring feature flag.')}),
    NP({'Package':T('h2'),'CVE ID':R('CVE-2026-1102'),'Severity':S('Medium'),'Triage Status':R('Patched'),'Version':R('0.4.2 → 0.4.3'),'AI Triage':R('Medium priority: HTTP/2 CONTINUATION frame flood can cause memory exhaustion. Patched in h2 0.4.3. ENGRAM webhook endpoint uses HTTP/1.1 primarily, but the Notion API client uses HTTP/2, making this relevant for outbound connections.')}),
    NP({'Package':T('axum'),'CVE ID':R('CVE-2026-0455'),'Severity':S('Low'),'Triage Status':R('Dismissed'),'Version':R('0.7.4'),'AI Triage':R('Low risk: Path traversal in static file serving middleware. Dismissed because ENGRAM does not use axum static file serving; all endpoints are dynamic API routes with explicit path matching.')}),
    NP({'Package':T('reqwest'),'CVE ID':R('CVE-2026-1290'),'Severity':S('Medium'),'Triage Status':R('Monitoring'),'Version':R('0.12.5'),'AI Triage':R('Medium risk: Open redirect in reqwest redirect following could be exploited if an attacker controls Notion webhook callback URLs. Monitoring because ENGRAM only makes outbound requests to known Notion and Claude API endpoints with hardcoded base URLs.')}),
    NP({'Package':T('chrono'),'CVE ID':R('CVE-2026-0201'),'Severity':S('Low'),'Triage Status':R('Accepted'),'Version':R('0.4.38'),'AI Triage':R('Low risk: Panic on malformed timezone strings in chrono parsing. Accepted because ENGRAM only parses ISO 8601 timestamps from Notion API responses which always use UTC offset format.')}),
    NP({'Package':T('openssl-sys'),'CVE ID':R('CVE-2026-1678'),'Severity':S('Critical'),'Triage Status':R('Patched'),'Version':R('0.9.100 → 0.9.101'),'AI Triage':R('Critical priority: Buffer overflow in OpenSSL X.509 certificate parsing allows remote code execution. Although ENGRAM primarily uses rustls, openssl-sys is pulled in transitively by some dependencies. Patched immediately to eliminate any code path exposure.')}),
    NP({'Package':T('tower-http'),'CVE ID':R('CVE-2026-0334'),'Severity':S('Low'),'Triage Status':R('Dismissed'),'Version':R('0.5.2'),'AI Triage':R('Low risk: CORS header injection via crafted Origin header. Dismissed because ENGRAM dashboard serves from localhost and CORS is configured with an explicit allowlist, not wildcard origins.')}),
    NP({'Package':T('jsonwebtoken'),'CVE ID':R('CVE-2026-0987'),'Severity':S('High'),'Triage Status':R('Patched'),'Version':R('9.2.0 → 9.3.0'),'AI Triage':R('High priority: Algorithm confusion attack allows HS256 tokens to be validated against RS256 public keys. ENGRAM uses JWT for dashboard authentication with ENGRAM_JWT_SECRET. Patch to 9.3.0 enforces strict algorithm matching and eliminates this attack vector.')}),
]},
'/api/dashboard/reviews': {results:[
    NP({'PR Title':T('Async webhook handler refactor'),'Author':R('Manoj P'),'Status':S('Merged'),'Blockers':N(0),'Suggestions':N(4),'Quality Score':N(92),'Review Draft':R('Well-structured migration from synchronous to channel-based webhook processing. The mpsc channel integration is clean with proper backpressure handling. Four suggestions focused on adding tracing spans to channel send/receive operations and documenting the 1024 buffer size rationale.')}),
    NP({'PR Title':T('Add JWT authentication middleware'),'Author':R('Manoj P'),'Status':S('Merged'),'Blockers':N(0),'Suggestions':N(3),'Quality Score':N(88),'Review Draft':R('Solid JWT middleware implementation using jsonwebtoken crate with proper HS256 algorithm enforcement. Suggestions include adding token refresh logic, configurable expiration times, and rate limiting on the /auth/login endpoint to prevent brute-force attacks.')}),
    NP({'PR Title':T('Fix race condition in event router'),'Author':R('Sarah Chen'),'Status':S('Merged'),'Blockers':N(1),'Suggestions':N(2),'Quality Score':N(85),'Review Draft':R('Addresses a critical race condition where concurrent agent spawns could receive duplicate events. The fix uses an atomic event counter with compare-and-swap. One blocker identified: the original fix did not handle the edge case where an agent crashes mid-processing, potentially losing events.')}),
    NP({'PR Title':T('Add OpenTelemetry instrumentation'),'Author':R('Alex Kim'),'Status':S('Open'),'Blockers':N(2),'Suggestions':N(5),'Quality Score':N(71),'Review Draft':R('Ambitious instrumentation PR that adds tracing spans across all agent boundaries. Two blockers: the 100% trace sampling rate will generate excessive data in production, and the span context propagation across async boundaries uses an incorrect parent context. Five suggestions cover span naming conventions and attribute standardization.')}),
    NP({'PR Title':T('Implement graceful shutdown signals'),'Author':R('James Liu'),'Status':S('Merged'),'Blockers':N(0),'Suggestions':N(1),'Quality Score':N(95),'Review Draft':R('Excellent implementation of coordinated shutdown using tokio::sync::watch channels. All nine agents properly drain their work queues before signaling completion. Clean separation between graceful and forced shutdown paths. One minor suggestion to log the shutdown reason.')}),
    NP({'PR Title':T('Update serde_json to fix deser regression'),'Author':R('Manoj P'),'Status':S('Merged'),'Blockers':N(0),'Suggestions':N(0),'Quality Score':N(97),'Review Draft':R('Minimal, focused dependency bump from serde_json 1.0.113 to 1.0.114 that resolves the 12% deserialization performance regression. Includes a benchmark test that validates the fix. No suggestions — this is a model dependency update PR.')}),
    NP({'PR Title':T('Add rate limiter to /webhook/github'),'Author':R('Sarah Chen'),'Status':S('Merged'),'Blockers':N(0),'Suggestions':N(2),'Quality Score':N(89),'Review Draft':R('Clean tower middleware integration for token bucket rate limiting. The per-IP tracking enhancement is well-implemented using a DashMap for concurrent access. Two suggestions: add rate limit headers to responses and consider Redis-backed distributed rate limiting for multi-instance deployments.')}),
    NP({'PR Title':T('Refactor config hot-reload mechanism'),'Author':R('Priya Sharma'),'Status':S('Open'),'Blockers':N(1),'Suggestions':N(3),'Quality Score':N(74),'Review Draft':R('Replaces file polling with inotify-based config watching for lower latency hot-reload. One blocker: the current implementation does not validate the new config before applying it, which could crash the daemon on malformed TOML. Suggestions include adding a config validation step, rollback on parse failure, and debouncing rapid file changes.')}),
    NP({'PR Title':T('Add Prometheus metrics endpoint'),'Author':R('Alex Kim'),'Status':S('Open'),'Blockers':N(0),'Suggestions':N(6),'Quality Score':N(78),'Review Draft':R('Adds a /metrics endpoint exposing agent execution counts, Notion API latency histograms, and webhook throughput gauges. No blockers but six suggestions cover metric naming conventions (should follow Prometheus best practices), adding help text to all metrics, and reducing cardinality on the route label.')}),
    NP({'PR Title':T('Fix dashboard WebSocket reconnection'),'Author':R('James Liu'),'Status':S('Closed'),'Blockers':N(0),'Suggestions':N(1),'Quality Score':N(82),'Review Draft':R('Fixes dashboard WebSocket auto-reconnection with exponential backoff. Closed in favor of a more comprehensive approach that also handles authentication token refresh on reconnect. The reconnection logic itself was sound with proper jitter.')}),
]},
'/api/dashboard/modules': {results:[
    NP({'Module Name':T('engram-core'),'Summary':R('Main daemon: HTTP server, webhook listener, event router, scheduler, and agent orchestration'),'Complexity Score':N(8.5),'Status':R('Documented'),'Key Files':R('src/main.rs, src/webhook.rs, src/router.rs, src/scheduler.rs, src/agents/mod.rs'),'Last Updated':R(D(0).slice(0,10))}),
    NP({'Module Name':T('engram-decisions'),'Summary':R('RFC lifecycle management, architecture decision records, and automated approval workflows'),'Complexity Score':N(6.2),'Status':R('Documented'),'Key Files':R('src/rfc.rs, src/adr.rs, src/approval.rs, src/drift.rs'),'Last Updated':R(D(1).slice(0,10))}),
    NP({'Module Name':T('engram-pulse'),'Summary':R('Performance benchmarking, regression detection, and baseline tracking with historical trends'),'Complexity Score':N(7.1),'Status':R('Documented'),'Key Files':R('src/benchmark.rs, src/regression.rs, src/baseline.rs, src/trend.rs'),'Last Updated':R(D(2).slice(0,10))}),
    NP({'Module Name':T('engram-shield'),'Summary':R('Security auditing: dependency scanning, CVE tracking, and vulnerability triage automation'),'Complexity Score':N(7.8),'Status':R('Documented'),'Key Files':R('src/audit.rs, src/cve.rs, src/triage.rs, src/advisory.rs'),'Last Updated':R(D(0).slice(0,10))}),
    NP({'Module Name':T('engram-atlas'),'Summary':R('Codebase mapping, module dependency graphs, and onboarding track generation'),'Complexity Score':N(6.9),'Status':R('Documented'),'Key Files':R('src/mapper.rs, src/graph.rs, src/onboarding.rs, src/knowledge_gap.rs'),'Last Updated':R(D(2).slice(0,10))}),
    NP({'Module Name':T('engram-vault'),'Summary':R('Environment config tracking, secret rotation monitoring, and drift detection'),'Complexity Score':N(5.4),'Status':R('Documented'),'Key Files':R('src/env.rs, src/rotation.rs, src/drift.rs, src/classifier.rs'),'Last Updated':R(D(1).slice(0,10))}),
    NP({'Module Name':T('engram-review'),'Summary':R('AI-powered code review: pattern detection, blocker identification, and review playbook enforcement'),'Complexity Score':N(7.5),'Status':R('Documented'),'Key Files':R('src/reviewer.rs, src/patterns.rs, src/playbook.rs, src/claude_prompt.rs'),'Last Updated':R(D(0).slice(0,10))}),
    NP({'Module Name':T('engram-health'),'Summary':R('Engineering health scoring, weekly digest generation, and cross-layer aggregation'),'Complexity Score':N(6.0),'Status':R('Documented'),'Key Files':R('src/scoring.rs, src/digest.rs, src/aggregator.rs'),'Last Updated':R(D(1).slice(0,10))}),
    NP({'Module Name':T('engram-timeline'),'Summary':R('Event timeline tracking and milestone management across all layers'),'Complexity Score':N(4.8),'Status':R('Documented'),'Key Files':R('src/event.rs, src/milestone.rs, src/timeline.rs'),'Last Updated':R(D(3).slice(0,10))}),
    NP({'Module Name':T('engram-release'),'Summary':R('Release readiness gates, version tracking, and deployment checklist automation'),'Complexity Score':N(5.2),'Status':R('Documented'),'Key Files':R('src/gate.rs, src/version.rs, src/checklist.rs, src/changelog.rs'),'Last Updated':R(D(5).slice(0,10))}),
    NP({'Module Name':T('engram-types'),'Summary':R('Shared types, config structs, Notion schema definitions, and client abstractions'),'Complexity Score':N(3.1),'Status':R('Documented'),'Key Files':R('src/lib.rs, src/config.rs, src/notion_schema.rs, src/client.rs'),'Last Updated':R(D(2).slice(0,10))}),
]},
'/api/dashboard/onboarding-tracks': {results:[
    NP({'Track Name':T('Backend Rust Engineer Onboarding'),'Role':R('Backend'),'Step Count':N(12),'Estimated Hours':N(40)}),
    NP({'Track Name':T('DevOps & Infrastructure'),'Role':R('DevOps'),'Step Count':N(8),'Estimated Hours':N(24)}),
    NP({'Track Name':T('Security Engineer Fast-Track'),'Role':R('Security'),'Step Count':N(6),'Estimated Hours':N(16)}),
]},
'/api/dashboard/onboarding-steps': {results:[
    NP({'Step Title':T('Clone repo and run cargo build'),'Week/Day':R('Week 1 / Day 1'),'Type':R('Environment Setup'),'Description':R('Set up Rust toolchain, clone ENGRAM repo, verify build succeeds'),'Estimated Time':N(60),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Read ENGRAM architecture overview'),'Week/Day':R('Week 1 / Day 1'),'Type':R('Reading'),'Description':R('Understand the 9-layer agent architecture and event routing system'),'Estimated Time':N(45),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Explore engram-core crate structure'),'Week/Day':R('Week 1 / Day 2'),'Type':R('Code Exploration'),'Description':R('Walk through main.rs, webhook.rs, and the agent spawn macro'),'Estimated Time':N(90),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Add a test webhook handler'),'Week/Day':R('Week 1 / Day 2'),'Type':R('Hands-on Task'),'Description':R('Create a simple endpoint that receives a GitHub webhook and logs the payload'),'Estimated Time':N(120),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Study Notion API integration'),'Week/Day':R('Week 1 / Day 3'),'Type':R('Reading'),'Description':R('Understand how NotionMcpClient queries and creates database pages'),'Estimated Time':N(60),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Implement a dashboard query endpoint'),'Week/Day':R('Week 1 / Day 3'),'Type':R('Hands-on Task'),'Description':R('Add a new /api/dashboard/* endpoint using the dashboard_query! macro'),'Estimated Time':N(90),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Read Claude AI integration code'),'Week/Day':R('Week 1 / Day 4'),'Type':R('Code Exploration'),'Description':R('Understand how ClaudeClient sends prompts and parses structured responses'),'Estimated Time':N(45),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Run the full test suite'),'Week/Day':R('Week 1 / Day 5'),'Type':R('Hands-on Task'),'Description':R('Execute cargo test across all crates, understand test patterns'),'Estimated Time':N(60),'Auto-generated':CK(true)}),
    NP({'Step Title':T('Shadow a code review'),'Week/Day':R('Week 2 / Day 1'),'Type':R('Reading'),'Description':R('Observe how engram-review agent analyzes PRs and generates feedback'),'Estimated Time':N(30),'Auto-generated':CK(false)}),
    NP({'Step Title':T('Fix a starter bug'),'Week/Day':R('Week 2 / Day 2'),'Type':R('Hands-on Task'),'Description':R('Pick a "good first issue" and submit a PR with tests'),'Estimated Time':N(180),'Auto-generated':CK(false)}),
]},
'/api/dashboard/knowledge-gaps': {results:[
    NP({'Gap Title':T('No owner for cryptography module'),'Type':R('Ownership'),'Severity':S('High'),'Status':S('Open'),'Detected At':R(D(3).slice(0,10))}),
    NP({'Gap Title':T('Missing docs for event routing protocol'),'Type':R('Documentation'),'Severity':S('Medium'),'Status':S('In Progress'),'Detected At':R(D(5).slice(0,10))}),
    NP({'Gap Title':T('Single point of knowledge: Notion API'),'Type':R('Bus Factor'),'Severity':S('High'),'Status':S('Open'),'Detected At':R(D(7).slice(0,10))}),
    NP({'Gap Title':T('No runbook for production deployment'),'Type':R('Operations'),'Severity':S('Critical'),'Status':S('In Progress'),'Detected At':R(D(10).slice(0,10))}),
    NP({'Gap Title':T('Test coverage gap in scheduler module'),'Type':R('Testing'),'Severity':S('Medium'),'Status':S('Resolved'),'Detected At':R(D(14).slice(0,10))}),
]},
'/api/dashboard/env-config': {results:[
    NP({'Var Name':T('NOTION_MCP_TOKEN'),'Environment':R('Production'),'Status':S('Active'),'Rotation Policy':R('90 days'),'Sensitivity':S('High'),'AI Classification':R('Primary authentication token for Notion MCP integration. Grants read/write access to all ENGRAM databases in the workspace. Compromise would allow unauthorized modification of engineering intelligence data.'),'Last Rotated':R(D(12).slice(0,10))}),
    NP({'Var Name':T('ANTHROPIC_API_KEY'),'Environment':R('Production'),'Status':S('Active'),'Rotation Policy':R('Never'),'Sensitivity':S('High'),'AI Classification':R('Claude API key used for AI-powered code review, RFC drift analysis, and health narrative generation. Usage is metered and billed per token. No rotation policy set because Anthropic keys are long-lived by design.'),'Last Rotated':R('N/A')}),
    NP({'Var Name':T('GITHUB_TOKEN'),'Environment':R('Production'),'Status':S('Active'),'Rotation Policy':R('90 days'),'Sensitivity':S('High'),'AI Classification':R('GitHub personal access token with repo and webhook scopes. Used for PR analysis, commit history fetching, and webhook validation. Compromise could expose private repository contents and allow unauthorized webhook registration.'),'Last Rotated':R(D(18).slice(0,10))}),
    NP({'Var Name':T('WEBHOOK_SECRET'),'Environment':R('Production'),'Status':S('Active'),'Rotation Policy':R('180 days'),'Sensitivity':S('Medium'),'AI Classification':R('HMAC-SHA256 shared secret for validating GitHub webhook payload signatures. Prevents unauthorized event injection into the ENGRAM pipeline. Lower rotation frequency acceptable since compromise only allows event spoofing, not data exfiltration.'),'Last Rotated':R(D(45).slice(0,10))}),
    NP({'Var Name':T('ENGRAM_JWT_SECRET'),'Environment':R('Production'),'Status':S('Active'),'Rotation Policy':R('365 days'),'Sensitivity':S('High'),'AI Classification':R('HMAC key for signing dashboard authentication JWT tokens. Compromise allows forging admin sessions and full dashboard access. Annual rotation is acceptable given the local-only deployment model.'),'Last Rotated':R(D(60).slice(0,10))}),
    NP({'Var Name':T('DATABASE_URL'),'Environment':R('Production'),'Status':S('Active'),'Rotation Policy':R('Never'),'Sensitivity':S('Medium'),'AI Classification':R('PostgreSQL connection string containing host, port, database name, and credentials. Used by connection pool for benchmark history and event persistence. Static credential since the database is network-isolated.'),'Last Rotated':R('N/A')}),
    NP({'Var Name':T('REDIS_URL'),'Environment':R('Production'),'Status':S('Missing In Prod'),'Rotation Policy':R('Never'),'Sensitivity':S('Medium'),'AI Classification':R('Redis connection URL for distributed rate limiting and session caching. Currently missing in production which causes fallback to in-memory rate limiting. This drift must be resolved before multi-instance deployment.'),'Last Rotated':R('N/A')}),
    NP({'Var Name':T('SENTRY_DSN'),'Environment':R('Staging'),'Status':S('Active'),'Rotation Policy':R('Never'),'Sensitivity':S('Low'),'AI Classification':R('Sentry Data Source Name for error tracking and performance monitoring in staging. Low sensitivity since the DSN only allows sending events to a specific Sentry project, not reading them.'),'Last Rotated':R('N/A')}),
    NP({'Var Name':T('NOTION_MCP_TOKEN'),'Environment':R('Staging'),'Status':S('Active'),'Rotation Policy':R('90 days'),'Sensitivity':S('High'),'AI Classification':R('Staging-specific Notion token scoped to a separate test workspace. Isolates staging agent writes from production data. Shares the same rotation cadence as the production token for policy consistency.'),'Last Rotated':R(D(20).slice(0,10))}),
    NP({'Var Name':T('SMTP_PASSWORD'),'Environment':R('Production'),'Status':S('Active'),'Rotation Policy':R('90 days'),'Sensitivity':S('Medium'),'AI Classification':R('SMTP authentication credential for sending digest notification emails. Used by the health agent to distribute weekly engineering digests. Medium sensitivity because scope is limited to outbound email delivery.'),'Last Rotated':R(D(30).slice(0,10))}),
]},
'/api/dashboard/releases': {results:[
    NP({'Version':T('v0.5.0'),'Status':R('Planning'),'Milestone':R('Q2 2026'),'All Tests Pass':CK(false),'Regression Free':CK(false),'No Critical CVEs':CK(false),'Release Notes':R('## v0.5.0 (Planned)\n- OpenTelemetry distributed tracing across all agents\n- Feature flag system for experimental agents\n- Database connection pooling with deadpool\n- Prometheus metrics endpoint'),'Migration Notes':R('- New OTEL_ENDPOINT environment variable required\n- Config schema adds [telemetry] section to engram.toml\n- Feature flags require updating Cargo.toml feature declarations'),'AI Readiness':R('Not ready for release. Three RFCs still in draft or review stage. OpenTelemetry PR has two unresolved blockers including incorrect span context propagation. Feature flag approach (compile-time vs runtime) not yet decided. Recommend completing RFC-013 review before scoping this release.')}),
    NP({'Version':T('v0.4.0-rc1'),'Status':R('Candidate'),'Milestone':R('Apr 2026'),'All Tests Pass':CK(true),'Regression Free':CK(true),'No Critical CVEs':CK(true),'Release Notes':R('## v0.4.0-rc1\n- Zero-copy API response deserialization (RFC-015)\n- Async webhook channel migration (RFC-014)\n- JWT dashboard authentication\n- Rate limiting on webhook endpoints\n- Graceful shutdown for all agents'),'Migration Notes':R('- ENGRAM_JWT_SECRET environment variable now required\n- Webhook handler response format changed from sync to async acknowledgment\n- Rate limit headers added to /webhook/github responses\n- Shutdown timeout configurable via [server.shutdown_timeout_secs] in engram.toml'),'AI Readiness':R('Release candidate is ready for final validation. All tests pass, no benchmark regressions detected, and zero critical CVEs outstanding. The JWT authentication and rate limiting features have been load-tested. Recommend a 48-hour soak test in staging before promoting to stable.')}),
    NP({'Version':T('v0.3.0'),'Status':R('Released'),'Milestone':R('Mar 2026'),'All Tests Pass':CK(true),'Regression Free':CK(true),'No Critical CVEs':CK(true),'Release Notes':R('## v0.3.0\n- Engineering health scoring with AI narrative generation\n- Weekly digest email delivery\n- Dashboard WebSocket live updates\n- CVE triage automation with AI recommendations\n- engram-release module for release gate management'),'Migration Notes':R('- New [health] and [digest] sections in engram.toml\n- SMTP_PASSWORD environment variable required for digest emails\n- Dashboard now requires WebSocket support on reverse proxy'),'AI Readiness':R('Successfully released on schedule. All release gate criteria passed including test coverage, benchmark baselines, and CVE audit. Post-release monitoring showed no issues in the first 72 hours.')}),
    NP({'Version':T('v0.2.0'),'Status':R('Released'),'Milestone':R('Feb 2026'),'All Tests Pass':CK(true),'Regression Free':CK(false),'No Critical CVEs':CK(true),'Release Notes':R('## v0.2.0\n- Codebase mapping and dependency graph visualization\n- Onboarding track auto-generation\n- Knowledge gap detection\n- Secret rotation monitoring\n- Environment drift detection'),'Migration Notes':R('- New [atlas] and [vault] sections in engram.toml\n- NOTION_MCP_TOKEN requires additional database permissions for Atlas and Vault databases\n- Existing Notion workspace needs two new databases created via /api/setup'),'AI Readiness':R('Released with a known benchmark regression in module graph traversal. The regression was minor (8% slower on large repos) and deemed acceptable for the feature value delivered. Fixed in a subsequent patch release.')}),
    NP({'Version':T('v0.1.0'),'Status':R('Released'),'Milestone':R('Jan 2026'),'All Tests Pass':CK(true),'Regression Free':CK(true),'No Critical CVEs':CK(true),'Release Notes':R('## v0.1.0\n- Initial release of ENGRAM engineering intelligence platform\n- Core daemon with webhook listener and agent scheduler\n- RFC lifecycle management (Decisions layer)\n- Benchmark tracking and regression detection (Pulse layer)\n- Dependency scanning and CVE tracking (Shield layer)'),'Migration Notes':R('- Fresh installation: run cargo install engram and configure engram.toml\n- Required environment variables: NOTION_MCP_TOKEN, ANTHROPIC_API_KEY, GITHUB_TOKEN\n- Run engram setup to initialize Notion databases'),'AI Readiness':R('Initial release met all quality gates. Core architecture proven stable through two weeks of internal dogfooding. Three foundational layers operational with clean dependency audit.')}),
]},
'/api/dashboard/benchmarks': {results:[
    NP({'Metric Name':T('webhook_handler_latency'),'Value':N(2.3),'Unit':R('ms'),'Delta Pct':N(-5.2),'Baseline':N(2.43),'Status':S('Normal')}),
    NP({'Metric Name':T('notion_api_query'),'Value':N(145),'Unit':R('ms'),'Delta Pct':N(1.8),'Baseline':N(142.4),'Status':S('Normal')}),
    NP({'Metric Name':T('event_router_dispatch'),'Value':N(0.15),'Unit':R('ms'),'Delta Pct':N(-2.1),'Baseline':N(0.153),'Status':S('Normal')}),
    NP({'Metric Name':T('agent_spawn_throughput'),'Value':N(12500),'Unit':R('ops/sec'),'Delta Pct':N(3.4),'Baseline':N(12088),'Status':S('Normal')}),
    NP({'Metric Name':T('health_score_aggregation'),'Value':N(8.7),'Unit':R('ms'),'Delta Pct':N(0.5),'Baseline':N(8.66),'Status':S('Normal')}),
    NP({'Metric Name':T('serde_json_deserialize'),'Value':N(4.1),'Unit':R('ms'),'Delta Pct':N(8.2),'Baseline':N(3.79),'Status':S('Warning'),'AI Impact':R('Deserialization latency increased 8.2% after serde_json 1.0.114 update. The regression is within the warning threshold but trending upward. Monitor closely and consider enabling zero-copy deserialization from RFC-015 to offset this overhead.')}),
    NP({'Metric Name':T('jwt_token_validation'),'Value':N(0.82),'Unit':R('ms'),'Delta Pct':N(6.9),'Baseline':N(0.767),'Status':S('Warning'),'AI Impact':R('JWT validation overhead increased after switching to strict algorithm matching in jsonwebtoken 9.3.0. The additional algorithm check adds roughly 50 microseconds per validation. Acceptable trade-off for the security improvement but warrants optimization if auth middleware becomes a bottleneck.')}),
    NP({'Metric Name':T('module_graph_traversal'),'Value':N(23.4),'Unit':R('ms'),'Delta Pct':N(14.7),'Baseline':N(20.4),'Status':S('Regressed'),'AI Impact':R('Module dependency graph traversal regressed 14.7% after adding transitive dependency tracking in engram-atlas. The BFS algorithm now visits significantly more nodes. Recommend switching to a bidirectional search or caching the traversal result since the module graph changes infrequently.')}),
]},
'/api/dashboard/tech-debt': {results:[
    NP({'Item':T('Replace unwrap() calls with proper error handling in webhook.rs'),'Severity':S('Medium'),'Status':S('Open'),'Module':R('engram-core'),'Description':R('webhook.rs contains 14 unwrap() calls on Result types from JSON parsing and channel sends. Any malformed webhook payload or full channel buffer will panic the entire daemon process, requiring a restart and losing in-flight events.'),'Frequency':N(14),'Category':S('Pattern'),'AI Recommendation':R('Replace all unwrap() calls with proper error propagation using the ? operator and a custom WebhookError enum. For channel sends, use try_send() with a fallback to a dead-letter queue. Estimated effort: 4 hours.')}),
    NP({'Item':T('Consolidate duplicate Notion query builders'),'Severity':S('Low'),'Status':S('Open'),'Module':R('engram-types'),'Description':R('Six different agents each implement their own Notion database query builder with nearly identical filter and sort logic. This duplication leads to inconsistent query patterns and makes schema changes require updates in multiple files.'),'Frequency':N(6),'Category':S('Architecture'),'AI Recommendation':R('Extract a generic NotionQueryBuilder with a builder pattern that supports filter chaining and sort configuration. Each agent can then compose queries from shared primitives. Estimated effort: 6 hours with a dedicated refactoring PR.')}),
    NP({'Item':T('Add integration tests for scheduler cron jobs'),'Severity':S('High'),'Status':S('In Progress'),'Module':R('engram-core'),'Description':R('The scheduler cron system has zero integration test coverage. Unit tests mock the time source but never verify that agents are actually spawned at the correct intervals. A regression in cron parsing went undetected for two weeks.'),'Frequency':N(1),'Category':S('Testing'),'AI Recommendation':R('Use tokio::time::pause() to create deterministic time-based integration tests. Write tests that advance time by specific intervals and assert agent spawn counts. Add a CI job that runs scheduler tests with --test-threads=1 to prevent timing flakiness.')}),
]},
'/api/dashboard/digest': {results:[
    NP({'Period':T('Week 13 — Mar 23-28, 2026'),'Summary':R('3 RFCs merged, 1 critical CVE patched, benchmark regression resolved. Overall health score improved to 87.'),'Key Risks':R('Cryptography module lacks an owner creating bus factor risk, REDIS_URL missing in production blocks multi-instance scaling, module graph traversal regression at 14.7% needs architectural fix'),'Key Wins':R('Zero critical CVEs after hyper and openssl-sys patches, three RFCs approved including zero-copy deserialization, code review velocity up 18% with AI-assisted reviews, release candidate v0.4.0-rc1 passed all gate checks'),'Recommendations':R('1. Assign a cryptography module owner before next sprint to mitigate bus factor risk. 2. Provision REDIS_URL in production to enable distributed rate limiting ahead of v0.5.0. 3. Investigate bidirectional search for module graph traversal to resolve the 14.7% regression. 4. Schedule a security review of JWT authentication before promoting v0.4.0-rc1 to stable. 5. Begin RFC-013 OpenTelemetry review to unblock v0.5.0 planning.')}),
]},
'/api/projects': {results:[
    NP({'Project Name':T('ENGRAM'),'Status':S('Active'),'Repository':R('manojpisini/engram')}),
]},
'/api/github/connection': {connected:true, repos:['manojpisini/engram']},
'/api/notion/connection': {connected:true, workspace_id:'demo-workspace-engram-2026'},
'/api/config': {auth:{notion_configured:true,anthropic_configured:true,github_configured:true,webhook_secret_set:true},claude:{model:'claude-sonnet-4-20250514'},server:{host:'127.0.0.1',port:3000}},
'/api/github/repos': [{name:'engram',full_name:'manojpisini/engram',description:'Engineering Intelligence, etched in Notion — AI-powered engineering platform',html_url:'https://github.com/manojpisini/engram',stargazers_count:142,forks_count:18,watchers_count:142,open_issues_count:12,language:'Rust',default_branch:'main',topics:['rust','notion','engineering-intelligence','ai','claude']}],
'/api/setup/status': {initialized:true,databases_initialized:true,notion_ready:true},
'/api/auth/status': {has_account:true,username:'admin'},
};

// ── GitHub sub-endpoints for demo ──
window.DEMO_GH_PULLS=[
    {number:142,title:'Async webhook handler refactor',user:{login:'manojpisini'},state:'closed',merged_at:D(0),updated_at:D(0)},
    {number:141,title:'Add OpenTelemetry instrumentation',user:{login:'alexkim'},state:'open',merged_at:null,updated_at:D(1)},
    {number:140,title:'Refactor config hot-reload mechanism',user:{login:'priyasharma'},state:'open',merged_at:null,updated_at:D(1)},
    {number:139,title:'Fix race condition in event router',user:{login:'sarahchen'},state:'closed',merged_at:D(2),updated_at:D(2)},
    {number:138,title:'Add JWT authentication middleware',user:{login:'manojpisini'},state:'closed',merged_at:D(3),updated_at:D(3)},
    {number:137,title:'Implement graceful shutdown signals',user:{login:'jamesliu'},state:'closed',merged_at:D(4),updated_at:D(4)},
    {number:136,title:'Update serde_json to fix deser regression',user:{login:'manojpisini'},state:'closed',merged_at:D(4),updated_at:D(4)},
    {number:135,title:'Add rate limiter to /webhook/github',user:{login:'sarahchen'},state:'closed',merged_at:D(5),updated_at:D(5)},
];
window.DEMO_GH_ISSUES=[
    {number:45,title:'Dashboard charts not rendering on Safari',user:{login:'alexkim'},state:'open',labels:[{name:'bug',color:'d73a4a'}],updated_at:D(0)},
    {number:44,title:'Add dark/light theme toggle',user:{login:'priyasharma'},state:'open',labels:[{name:'enhancement',color:'a2eeef'}],updated_at:D(1)},
    {number:43,title:'Webhook timeout on large payloads',user:{login:'jamesliu'},state:'open',labels:[{name:'bug',color:'d73a4a'},{name:'priority',color:'e4e669'}],updated_at:D(2)},
    {number:42,title:'Add Slack notification integration',user:{login:'sarahchen'},state:'open',labels:[{name:'feature',color:'0075ca'}],updated_at:D(3)},
    {number:41,title:'Memory leak in long-running scheduler',user:{login:'manojpisini'},state:'closed',labels:[{name:'bug',color:'d73a4a'},{name:'critical',color:'b60205'}],updated_at:D(5)},
    {number:40,title:'Documentation: add API reference',user:{login:'alexkim'},state:'open',labels:[{name:'documentation',color:'0075ca'}],updated_at:D(6)},
];
window.DEMO_GH_COMMITS=[
    {sha:'4e58640a1b',commit:{message:'Release standalone executables instead of archives',author:{name:'Manoj P',date:D(0)}}},
    {sha:'bbc0d0a3f2',commit:{message:'Fix packaging scripts to use engram.toml.example',author:{name:'Manoj P',date:D(0)}}},
    {sha:'f6af0e2c84',commit:{message:'Fix config deserialization: add serde defaults',author:{name:'Manoj P',date:D(0)}}},
    {sha:'6c8417a9d1',commit:{message:'Show setup wizard when databases not initialized',author:{name:'Manoj P',date:D(1)}}},
    {sha:'0795625b3e',commit:{message:'Fix Notion setup: require parent page ID',author:{name:'Manoj P',date:D(1)}}},
    {sha:'d496cec7f0',commit:{message:'Revert to working Notion page creation',author:{name:'Manoj P',date:D(2)}}},
    {sha:'cf65629a12',commit:{message:'Wire repo dropdown to filter all dashboard data',author:{name:'Sarah Chen',date:D(3)}}},
    {sha:'0a4095f5b8',commit:{message:'Fix Notion page creation and add repo dropdown',author:{name:'Alex Kim',date:D(4)}}},
    {sha:'a1b2c3d4e5',commit:{message:'Add benchmark regression detection for serde_json',author:{name:'James Liu',date:D(5)}}},
    {sha:'f6g7h8i9j0',commit:{message:'Implement secret rotation logging in Vault agent',author:{name:'Priya Sharma',date:D(6)}}},
];
window.DEMO_GH_CONTRIBUTORS=[
    {login:'manojpisini',avatar_url:'https://ui-avatars.com/api/?name=MP&background=f59e0b&color=000&size=40',contributions:187},
    {login:'sarahchen',avatar_url:'https://ui-avatars.com/api/?name=SC&background=3b82f6&color=fff&size=40',contributions:64},
    {login:'alexkim',avatar_url:'https://ui-avatars.com/api/?name=AK&background=22c55e&color=fff&size=40',contributions:41},
    {login:'jamesliu',avatar_url:'https://ui-avatars.com/api/?name=JL&background=8b5cf6&color=fff&size=40',contributions:28},
    {login:'priyasharma',avatar_url:'https://ui-avatars.com/api/?name=PS&background=ec4899&color=fff&size=40',contributions:19},
];

// ── getDemoData ──
window.getDemoData = function(path){
    if(window.DEMO_DATA[path]) return structuredClone(window.DEMO_DATA[path]);
    if(path.includes('/pulls')) return structuredClone(window.DEMO_GH_PULLS);
    if(path.includes('/issues')) return structuredClone(window.DEMO_GH_ISSUES);
    if(path.includes('/commits')) return structuredClone(window.DEMO_GH_COMMITS);
    if(path.includes('/contributors')) return structuredClone(window.DEMO_GH_CONTRIBUTORS);
    return {results:[]};
};

// ── toggleDemo ──
window.toggleDemo = function(){
    window.demoMode=!window.demoMode;
    var btn=document.getElementById('demoBtn');
    if(window.demoMode){
        btn.style.background='#f59e0b'; btn.style.color='#000'; btn.style.borderColor='#f59e0b'; btn.textContent='DEMO ON';
        document.getElementById('statusDot').className='status-dot on';
        document.getElementById('statusText').textContent='Demo Mode';
        window.currentUser={username:'admin',display_name:'Manoj P',email:'manoj@engram.dev',role:'admin',avatar_initials:'MP'};
        window.authToken='demo-token';
        if(window.updateUserUI) window.updateUserUI();
        if(window.fetchAll) window.fetchAll();
    } else {
        btn.style.background='var(--surface2)'; btn.style.color='var(--text3)'; btn.style.borderColor='var(--border2)'; btn.textContent='Demo';
        window.authToken=localStorage.getItem('engram_token');
        if(window.initApp) window.initApp();
    }
};

})();
